#%RAML 1.0
title: Tracks
version: v1
baseUri: https://api.github.com
mediaType: application/json

types:
  Track: !include includes/track.json

uses:
  TracksLib: includes/tracks-library.raml

/tracks:
  description: The search resource
  get:
    responses:
        200:
          body:
            application/json:
              type: Track[]
  post:
    body:
      application/json:
        type: Track

  /{id}:
    uriParameters:
      id: string
    get:
      responses:
        200:
          body:
            application/json:
              type: TracksLib.Track
